In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/USDA.csv')

In [3]:
df.head()

,ID,Description,Calories,Protein,TotalFat,Carbohydrate,Sodium,SaturatedFat,Cholesterol,Sugar,Calcium,Iron,Potassium,VitaminC,VitaminE,VitaminD
0,1001,"BUTTER,WITH SALT",717.0,0.85,81.11,0.06,714.0,51.368,215.0,0.06,24.0,0.02,24.0,0.0,2.32,1.5
1,1002,"BUTTER,WHIPPED,WITH SALT",717.0,0.85,81.11,0.06,827.0,50.489,219.0,0.06,24.0,0.16,26.0,0.0,2.32,1.5
2,1003,"BUTTER OIL,ANHYDROUS",876.0,0.28,99.48,0.00,2.0,61.924,256.0,0.00,4.0,0.00,5.0,0.0,2.80,1.8
3,1004,"CHEESE,BLUE",353.0,21.40,28.74,2.34,1395.0,18.669,75.0,0.50,528.0,0.31,256.0,0.0,0.25,0.5
4,1005,"CHEESE,BRICK",371.0,23.24,29.68,2.79,560.0,18.764,94.0,0.51,674.0,0.43,136.0,0.0,0.26,0.5

In [4]:
df.dtypes

ID                int64
Description      object
Calories        float64
Protein         float64
TotalFat        float64
Carbohydrate    float64
Sodium          float64
SaturatedFat    float64
Cholesterol     float64
Sugar           float64
Calcium         float64
Iron            float64
Potassium       float64
VitaminC        float64
VitaminE        float64
VitaminD        float64
dtype: object

In [7]:
df.shape

(7058, 16)

In [9]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
ID,7058.0,14259.821196,8577.179705,1001.0,8387.250,13293.500,18336.750,93600.00
Calories,7057.0,219.695338,172.198755,0.0,85.000,181.000,331.000,902.00
Protein,7057.0,11.710368,10.919356,0.0,2.290,8.200,20.430,88.32
TotalFat,7057.0,10.320614,16.814191,0.0,0.720,4.370,12.700,100.00
Carbohydrate,7057.0,20.697860,27.630443,0.0,0.000,7.130,28.170,100.00
Sodium,6974.0,322.059220,1045.416931,0.0,37.000,79.000,386.000,38758.00
SaturatedFat,6757.0,3.452267,6.921267,0.0,0.172,1.256,4.028,95.60
Cholesterol,6770.0,41.551994,122.963028,0.0,0.000,3.000,69.000,3100.00
Sugar,5148.0,8.256540,15.361509,0.0,0.000,1.395,7.875,99.80
Calcium,6922.0,73.530627,222.445338,0.0,9.000,19.000,56.000,7364.00
Iron,6935.0,2.828368,6.019878,0.0,0.520,1.330,2.620,123.60
Potassium,6649.0,301.357949,415.638949,0.0,135.000,250.000,348.000,16500.00
VitaminC,6726.0,9.435980,71.256536,0.0,0.000,0.000,3.100,2400.00
VitaminE,4338.0,1.487462,5.386914,0.0,0.120,0.270,0.710,149.40
VitaminD,4224.0,0.576918,4.301147,0.0,0.000,0.000,0.100,250.00

#### Q: Which food has the highest sodium content?

In [21]:
df.Sodium.max()

38758.0

In [31]:
df.query("Sodium == 38758").loc[:, 'Description']

264    SALT,TABLE
Name: Description, dtype: object

#### A: Table Salt

#### Q: Which foods and how many foods have a sodium content > 10,000 mg?

In [32]:
df.query("Sodium > 10000")

,ID,Description,Calories,Protein,TotalFat,Carbohydrate,Sodium,SaturatedFat,Cholesterol,Sugar,Calcium,Iron,Potassium,VitaminC,VitaminE,VitaminD
264,2047,"SALT,TABLE",0.0,0.00,0.00,0.00,38758.0,0.000,0.0,0.00,24.0,0.33,8.0,0.0,0.00,0.0
921,6075,"SOUP,BF BROTH OR BOUILLON,PDR,DRY",213.0,15.97,8.89,17.40,26000.0,4.320,10.0,16.71,60.0,1.00,446.0,0.0,2.17,0.0
922,6076,"SOUP,BEEF BROTH,CUBED,DRY",170.0,17.30,4.00,16.10,24000.0,1.990,4.0,14.51,60.0,2.23,403.0,0.0,0.00,0.0
924,6080,"SOUP,CHICK BROTH OR BOUILLON,DRY",267.0,16.66,13.88,18.01,23875.0,3.430,13.0,17.36,187.0,1.03,309.0,1.1,0.46,0.0
925,6081,"SOUP,CHICK BROTH CUBES,DRY",198.0,14.60,4.70,23.50,24000.0,1.200,13.0,0.00,190.0,1.87,374.0,1.0,0.09,NaN
937,6115,"GRAVY,AU JUS,DRY",313.0,9.20,9.63,47.49,11588.0,2.026,4.0,NaN,140.0,9.30,279.0,1.0,NaN,NaN
1302,6979,ADOBO FRESCO,271.0,2.00,20.90,18.60,17152.0,2.910,0.0,2.03,123.0,3.20,187.0,5.8,2.69,0.0
5320,18369,"LEAVENING AGENTS,BAKING PDR,DOUBLE-ACTING,NA A...",53.0,0.00,0.00,27.70,10600.0,0.000,0.0,0.00,5876.0,11.02,20.0,0.0,0.00,0.0
5323,18372,"LEAVENING AGENTS,BAKING SODA",0.0,0.00,0.00,0.00,27360.0,0.000,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.0
5697,19225,"DESSERTS,RENNIN,TABLETS,UNSWTND",84.0,1.00,0.10,19.80,26050.0,0.041,0.0,NaN,3733.0,7.07,292.0,0.0,NaN,NaN

In [33]:
df.query("Sodium > 10000").shape

(10, 16)